services:
  ical-proxy:
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.ical-proxy.rule=Host(`${TRAEFIK_HOST:-ical-sync.ak-net.ru}`)
      - traefik.http.routers.ical-proxy.entrypoints=websecure
      - traefik.http.routers.ical-proxy.tls=true
      - traefik.http.services.ical-proxy.loadbalancer.server.port=${PORT:-3000}

networks:
  traefik:
    external: true
    name: traefik_default
