services:
  ical-proxy:
    container_name: ical-proxy
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-3000}:${PORT:-3000}"
